### ISSUE TITLE
What is the build version of the Win10 VM?

### ISSUE THREAD

**Issue by swthibodeau** [MicrosoftLearning/AZ-900T0x-MicrosoftAzureFundamentals#42] opened 2020-04-07 13:42 UTC
This isnt an "issue" per se, however I cannot find any documentation (in the MCT downloads) that spells out what the build version of the Win10 client should be used. 

I've run into an "issue" in one of the labs, but I don't believe its a Microsoft issue, vs the vendor we're using for the lab environment. I believe they're using an old build: 1709.

I have seen another vendor using build 1909. 

Can anyone point me to where the build version is documented?

thank you,
Scott

**Comment by polichtm** [comment] 2020-04-07 20:05
Hi Scott,
what specifically is the issue you ran into?
rgds
Marcin

**Comment by swthibodeau** [comment] 2020-04-07 22:07
Marcin,
thank you for the reply. 
The issue I ran into was that the PS lab wouldnt work as the build the vendor supplied uses PS 5.1. PS. 5.1 will not allow both AzureRM and the Az module to be loaded at the same time, so the install-module command would error out. I had used a different vendors VM and their build was 1909 which I believe is PS 6 which doesnt have the same issue. You may get a warning by having both installed, however the PS command as written in the lab instructions work properly. 

I did come up with a workaround on the 1709 build and that was to install PS 7 and run the PS commands from there, and they completed successfully. 

So...I wanted to circle back around to clarify as to what guidance MS provided for the VM build for the AZ-900 lab machine, as in what Windows 10 build. 

thank you,

Scott

**Comment by staleycyn** [comment] 2020-04-07 23:50
Hi Scott,

This course was designed to be taught without a hosted lab environment. Students simply connect to Azure and do the labs. There are two optional labs (M10 and M11) which require a local installation of PowerShell or the CLI. Those labs are being changed to only use the Cloud Shell. So, the answer is we did not provide any build instructions for a lab hoster, because we never intended the course to require/use a hosted lab. 

Write back if things are still not clear. - Cindy

**Comment by polichtm** [comment] 2020-04-26 01:57
Closing due to lack of further questions

**Closed by polichtm** 2020-04-26 01:57 UTC
